export const ROUTES = {
	DASHBOARD: 'DASHBOARD',
	LIST_CATEGORY: 'LIST_CATEGORY',
	CREATE_CATEGORY: 'CREATE_CATEGORY',
	VIEW_CATEGORY: 'VIEW_CATEGORY',	
	LIST_PRODUCT: 'LIST_PRODUCT',
	CREATE_PRODUCT: 'CREATE_PRODUCT',
	VIEW_PRODUCT: 'VIEW_PRODUCT',
	NOT_FOUND: 'NOT_FOUND',
};